# Basic options
title: Datamanju
author: Alan Luo
email: "alanluo@outlook.com"
description: Tech, Data and Life
github_username:  datamanju

# Build settings
markdown: kramdown
theme: minima

# Header Pages
header_pages:
  - about.md
  - README.md
