# basic options
title: Datamanju
author: Alan Luo
email: alan_l@datamanju.com
description: My Blog About Tech, Data and Life
github_username:  datamanju

# Build settings
markdown: kramdown
theme: minima
