# basic options
title: Alan Luo 
author: Alan Luo - Data Analyst
email: alanluo@outlook.com
description: Tech, Data and Life
github_username:  datamanju

# Build settings
markdown: kramdown
theme: minima
