# Basic options
title: Datamanju - A Portfolio Site
author: Alan Luo
email: "alanluo@outlook.com"
description: Tech, Data and Life
github_username:  datamanju

# Build settings
markdown: kramdown
theme: minami

# Header Pages
header_pages:
  - about.md
  - blog.md
